import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'th' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'th',
      setLanguage: (lang) => set({ language: lang }),
    }),
    {
      name: 'duit-language-storage',
    }
  )
);

export const translations = {
  th: {
    nav: {
      collections: 'สินค้าทั้งหมด',
      care: 'การดูแลสัตว์เลี้ยง',
      journal: 'บทความ',
      heritage: 'เกี่ยวกับเรา',
      viewStore: 'ดูร้านค้า',
      admin: 'ระบบหลังบ้าน',
    },
    hero: {
      discover: 'เลือกซื้อสินค้า',
      philosophy: 'ความตั้งใจของเรา',
      newCollection: 'คอลเลกชันใหม่ล่าสุด',
      bestSeller: 'สินค้าขายดี',
      livingSeries: 'ซีรีส์เพื่อการอยู่อาศัย',
      slide1Title: 'DESIGNED FOR BETTER LIVING.',
      slide1Sub: 'ยกระดับคุณภาพชีวิตสัตว์เลี้ยงที่คุณรัก ด้วยนวัตกรรมการออกแบบที่เน้นฟังก์ชันและความสวยงามสไตล์เกาหลี',
      slide2Title: 'PRECISION IN EVERY DROP.',
      slide2Sub: 'น้ำพุแมวอัจฉริยะที่ออกแบบมาเพื่อความเงียบสงบและการกรองน้ำที่สะอาดที่สุด',
      slide3Title: 'COZY SPACE FOR EXPLORERS.',
      slide3Sub: 'บ้านพักผ่อนทรงเต็นท์ที่มอบความรู้สึกปลอดภัยและอบอุ่น ออกแบบมาให้เป็นเฟอร์นิเจอร์ชิ้นหรูในบ้านคุณ',
    },
    shop: {
      explore: 'เลือกชมตามหมวดหมู่',
      viewAll: 'ดูทั้งหมด',
      allProducts: 'คอลเลกชันสินค้า',
      eatDrink: 'อาหารและน้ำ',
      furniture: 'เฟอร์นิเจอร์',
      playRest: 'เล่นและพักผ่อน',
      hygiene: 'สุขอนามัย',
      daily: 'ของใช้ทั่วไป',
      aList: 'สินค้าแนะนำ',
      curating: 'กำลังคัดสรรสินค้าชิ้นเอก...',
      freshArrivals: 'สินค้ามาใหม่',
      exploreAll: 'สำรวจทั้งหมด',
      categorySub: 'ค้นหาสิ่งที่ใช่สำหรับเพื่อนตัวน้อยของคุณ',
      selectionSub: 'รวบรวมสินค้าที่ได้รับความนิยมสูงสุด ด้วยดีไซน์ที่โดดเด่นและความงดงามที่ยั่งยืน',
      newArrivalsTitle: 'New In TH.',
      newArrivalsSub: 'สัมผัสวิวัฒนาการล่าสุดของงานดีไซน์จาก Duit รุ่นลิมิเต็ดที่ผลิตขึ้นอย่างประณีต',
      privateCircle: 'ไพรเวท เซอร์เคิล',
      exclusiveClub: 'สิทธิพิเศษสำหรับสมาชิก',
      membershipSub: 'ก้าวเข้าสู่โลกแห่งการดูแลสัตว์เลี้ยงที่ออกแบบมาเพื่อคุณโดยเฉพาะ รับสิทธิประโยชน์และบริการระดับพรีเมียม',
    },
    footer: {
      mission: 'นิยามใหม่ของชีวิตสัตว์เลี้ยงผ่านความแม่นยำทางสถาปัตยกรรมและความสวยงามที่ยั่งยืน ออกแบบในกรุงโซล เพื่อคุณภาพชีวิตที่ดีของสัตว์เลี้ยงทั่วโลก',
      directory: 'สารบัญเว็บไซต์',
      support: 'ความช่วยเหลือ',
      atelier: 'อาเตลิเย่',
      assistance: 'คำถามที่พบบ่อย',
      logistics: 'การจัดส่งสินค้า',
      concierge: 'ติดต่อสอบถาม',
      privacy: 'นโยบายความเป็นส่วนตัว',
      terms: 'ข้อกำหนดและเงื่อนไข',
      representative: 'ตัวแทนจำหน่ายอย่างเป็นทางการ',
    },
    crm: {
      memberCard: 'บัตรสมาชิก Duit Care+',
      tierLevel: 'ระดับสมาชิก',
      points: 'คะแนนสะสม',
      verifiedOwner: 'เจ้าของผลิตภัณฑ์ของแท้',
      welcomeTitle: 'ยินดีต้อนรับสู่',
      welcomeSubtitle: 'เริ่มต้นประสบการณ์สุดพิเศษที่คัดสรรมาเพื่อเพื่อนตัวโปรดของคุณ',
      initDiscovery: 'เริ่มสร้างโปรไฟล์',
      stage01: 'ขั้นตอนที่ 01',
      stage02: 'ขั้นตอนที่ 02',
      stage03: 'ขั้นตอนที่ 03',
      definePet: 'สัตว์เลี้ยงของคุณคือ?',
      visualIdentity: 'ภาพลักษณ์ของน้อง',
      uploadPortrait: 'อัปโหลดรูปภาพ',
      back: 'ย้อนกลับ',
      proceed: 'ถัดไป',
      dog: 'น้องหมา',
      cat: 'น้องแมว',
      detailedPortfolio: 'ข้อมูลประวัติน้อง',
      officialName: 'ชื่อน้อง',
      heritage: 'สายพันธุ์',
      classification: 'ขนาดตัว',
      generate: 'บันทึกและวิเคราะห์ข้อมูล',
      memberPavilion: 'หน้าสมาชิก',
      dashboardSubtitle: 'พื้นที่เฉพาะสำหรับสมาชิก Duit Care+ สัมผัสการดูแลที่คัดสรรมาเพื่อคุณและน้องโดยเฉพาะ',
      tabPersona: 'ข้อมูลน้อง',
      tabCollection: 'สินค้าของฉัน',
      tabPrivileges: 'สิทธิพิเศษ',
      identitySynthesis: 'วิเคราะห์ตัวตนน้อง',
      aiResult: 'ผลวิเคราะห์โดย AI',
      bespokeCuration: 'สินค้าที่แนะนำพิเศษ',
      recommended: 'แนะนำสำหรับน้อง',
      managedCollection: 'รายการสินค้าของคุณ',
      collectionSubtitle: 'จัดการข้อมูลสินค้าและการรับประกันได้ง่ายๆ ในที่เดียว',
      registerNew: 'ลงทะเบียนสินค้าเพิ่ม',
      privilegesPending: 'สิทธิพิเศษใหม่ๆ เร็วๆ นี้',
      invitationPending: 'เรากำลังเตรียมข้อเสนอและรางวัลสุดพิเศษสำหรับคุณ',
      resetProfile: 'สร้างโปรไฟล์ใหม่',
      selectBreed: 'เลือกสายพันธุ์',
      selectSize: 'เลือกขนาด',
      energyLevel: 'ระดับพลังงาน',
      designPreference: 'สไตล์ที่ชอบ',
      minimalist: 'มินิมอล',
      atelierManagement: 'ระบบจัดการหลังบ้าน',
      signOut: 'ออกจากระบบ',
      authenticating: 'กำลังยืนยันตัวตน...',
      warrantyActive: 'การรับประกันมีผลอยู่',
      designForRefined: 'ดีไซน์เพื่อความงดงามที่เหนือระดับ',
    },
    auth: {
      username: 'ชื่อผู้ใช้งาน',
      usernameHint: '(ตัวอักษรภาษาอังกฤษตัวเล็กหรือตัวเลข 4-16 ตัว)',
      email: 'อีเมล',
      emailHint: 'โปรดป้อนที่อยู่อีเมลที่คุณต้องการใช้เป็นรหัสล็อกอิน',
      password: 'รหัสผ่าน',
      passwordHint: '(อย่างน้อย 8 ตัวอักษร ประกอบด้วยตัวเลขและตัวอักษร)',
      confirmPassword: 'ยืนยันรหัสผ่าน',
      name: 'ชื่อ-นามสกุล',
      address: 'ที่อยู่',
      postalCode: 'รหัสไปรษณีย์',
      findAddress: 'ค้นหาที่อยู่',
      basicAddress: 'ที่อยู่พื้นฐาน (บ้านเลขที่, ถนน)',
      subdistrict: 'ตำบล/แขวง',
      district: 'อำเภอ/เขต',
      province: 'จังหวัด',
      detailAddress: 'ที่อยู่ส่วนที่เหลือ (กรอกข้อมูลเพิ่มเติมได้)',
      homePhone: 'โทรศัพท์บ้าน',
      mobilePhone: 'โทรศัพท์มือถือ',
      petRegistrationTitle: 'ลงทะเบียนข้อมูลสัตว์เลี้ยงและรับสิทธิประโยชน์',
      petBirthday: 'วันเกิดของสัตว์เลี้ยง',
      petNickname: 'ชื่อเล่น',
      petType: 'สัตว์เลี้ยง',
      petSize: 'ขนาดสัตว์เลี้ยง',
      referralCode: 'รหัสผู้แนะนำ',
      year: 'ปี',
      month: 'เดือน',
      day: 'วัน',
      birthdayHint: '(หากไม่ชัดเจน โปรดระบุวันที่รับเลี้ยง)',
      step1: 'ข้อมูลพื้นฐาน',
      step2: 'ข้อมูลสัตว์เลี้ยง',
    },
    common: {
      search: 'ค้นหา',
      cart: 'ตะกร้าสินค้า',
      petPortfolio: 'ข้อมูลสัตว์เลี้ยง',
      authenticate: 'เข้าสู่ระบบ',
      logout: 'ออกจากระบบ',
      save: 'บันทึกข้อมูล',
      membership: 'สมัครสมาชิก',
      bespokeCare: 'ดูแลอย่างใกล้ชิด',
      earlyAccess: 'สิทธิ์เข้าถึงก่อนใคร',
      heritageDesign: 'ดีไซน์ที่เป็นเอกลักษณ์',
      heritageDesc: 'สร้างสรรค์โดยสถาบันดีไซน์ในเกาหลีใต้ ด้วยปรัชญาความงามที่เหนือกาลเวลา',
      premiumIntegrity: 'คุณภาพระดับพรีเมียม',
      premiumDesc: 'เลือกใช้เฉพาะวัสดุเกรดการแพทย์ที่ดีที่สุด เพื่อความปลอดภัยของสัตว์เลี้ยง',
      globalConcierge: 'บริการดูแลระดับสากล',
      globalDesc: 'ประสบการณ์การจัดส่งที่ไร้รอยต่อ พร้อมการรับประกันสินค้าอย่างเป็นทางการ',
      directory: 'เมนูหลัก',
      signedOut: 'ออกจากระบบเรียบร้อยแล้ว',
    }
  },
  en: {
    nav: {
      collections: 'Collections',
      care: 'Duit Care',
      journal: 'Journal',
      heritage: 'About Us',
      viewStore: 'View Store',
      admin: 'Admin',
    },
    hero: {
      discover: 'Explore Collection',
      philosophy: 'Our Vision',
      newCollection: 'New Collection',
      bestSeller: 'Bestsellers',
      livingSeries: 'Living Series',
      slide1Title: 'DESIGNED FOR BETTER LIVING.',
      slide1Sub: 'Elevate your pet\'s quality of life with innovative designs focused on function and Korean aesthetic.',
      slide2Title: 'PRECISION IN EVERY DROP.',
      slide2Sub: 'An intelligent pet fountain engineered for silence and superior water filtration.',
      slide3Title: 'COZY SPACE FOR EXPLORERS.',
      slide3Sub: 'A tent-inspired sanctuary providing safety and warmth, crafted to be luxury furniture for your home.',
    },
    shop: {
      explore: 'Shop by Category',
      viewAll: 'View All',
      allProducts: 'All Products',
      eatDrink: 'Dining',
      furniture: 'Furniture',
      playRest: 'Play & Rest',
      hygiene: 'Hygiene',
      daily: 'Essentials',
      aList: 'Featured',
      curating: 'Curating Masterpieces...',
      freshArrivals: 'New Arrivals',
      exploreAll: 'Explore All',
      categorySub: 'Discover thoughtfully designed pieces for your companion.',
      selectionSub: 'A curated selection of our most popular designs, defined by craftsmanship and enduring appeal.',
      newArrivalsTitle: 'New in Thailand',
      newArrivalsSub: 'Experience the latest evolution of Duit design language. Precision-crafted, limited edition releases.',
      privateCircle: 'Private Circle',
      exclusiveClub: 'Exclusive Membership',
      membershipSub: 'Step into a world of bespoke pet care. Join Duit Care+ for personalized recommendations and elite benefits.',
    },
    footer: {
      mission: 'Redefining the standards of pet living through architectural precision and timeless aesthetic. Designed in Seoul, curated for the world.',
      directory: 'Sitemap',
      support: 'Customer Care',
      atelier: 'The Atelier',
      assistance: 'FAQ',
      logistics: 'Shipping',
      concierge: 'Contact Us',
      privacy: 'Privacy Policy',
      terms: 'Terms & Conditions',
      representative: 'Official Distributor',
    },
    crm: {
      memberCard: 'Duit Care+ Member',
      tierLevel: 'Membership Tier',
      points: 'Points Balance',
      verifiedOwner: 'Verified Duit Owner',
      welcomeTitle: 'Welcome to',
      welcomeSubtitle: 'Start a bespoke experience meticulously curated for your beloved companion.',
      initDiscovery: 'Create Profile',
      stage01: 'Step 01',
      stage02: 'Step 02',
      stage03: 'Step 03',
      definePet: 'Type of Companion',
      visualIdentity: 'Visual Identity',
      uploadPortrait: 'Upload Portrait',
      back: 'Back',
      proceed: 'Proceed',
      dog: 'Dog',
      cat: 'Cat',
      detailedPortfolio: 'Pet Profile',
      officialName: 'Pet Name',
      heritage: 'Breed',
      classification: 'Size',
      generate: 'Save & Analyze',
      memberPavilion: 'Member Area',
      dashboardSubtitle: 'Your private sanctuary for bespoke care and exclusive services.',
      tabPersona: 'Pet Profile',
      tabCollection: 'My Collection',
      tabPrivileges: 'Privileges',
      identitySynthesis: 'Personality Analysis',
      aiResult: 'AI Analysis Result',
      bespokeCuration: 'Recommended for You',
      recommended: 'Recommended',
      managedCollection: 'Your Collection',
      collectionSubtitle: 'Manage your products and warranty information in one place.',
      registerNew: 'Register Product',
      privilegesPending: 'Upcoming Privileges',
      invitationPending: 'We are preparing exclusive offers and rewards for you.',
      resetProfile: 'Reset Profile',
      selectBreed: 'Select Breed',
      selectSize: 'Select Size',
      energyLevel: 'Energy Level',
      designPreference: 'Design Preference',
      minimalist: 'Minimalist',
      atelierManagement: 'Atelier Management',
      signOut: 'Sign Out',
      authenticating: 'Authenticating...',
      warrantyActive: 'Warranty Active',
      designForRefined: 'Design for refined aesthetics',
    },
    auth: {
      username: 'Username',
      usernameHint: '(Lowercase English/Numbers 4-16 chars)',
      email: 'Email',
      emailHint: 'Please enter the email you wish to use as your login ID',
      password: 'Password',
      passwordHint: '(Mix at least 2: Upper/Lower, Numbers, Symbols 10-16 chars)',
      confirmPassword: 'Confirm Password',
      name: 'Name',
      address: 'Address',
      postalCode: 'Postal Code',
      findAddress: 'Find Address',
      basicAddress: 'Basic Address',
      detailAddress: 'Detailed Address (Optional)',
      homePhone: 'Home Phone',
      mobilePhone: 'Mobile Phone',
      petRegistrationTitle: 'Register your pet for exclusive rewards',
      petBirthday: 'Pet Birthday',
      petNickname: 'Pet Nickname',
      petType: 'Pet Type',
      petSize: 'Pet Size',
      referralCode: 'Referral Code',
      year: 'Year',
      month: 'Month',
      day: 'Day',
      birthdayHint: '(If unknown, use adoption date)',
      step1: 'Basic Info',
      step2: 'Pet Info',
    },
    common: {
      search: 'Search',
      cart: 'Shopping Bag',
      petPortfolio: 'Pet Profile',
      authenticate: 'Sign In',
      logout: 'Sign Out',
      save: 'Save Changes',
      membership: 'Join Membership',
      bespokeCare: 'Bespoke Care',
      earlyAccess: 'Early Access',
      heritageDesign: 'Signature Design',
      heritageDesc: 'Created by our Seoul design house with a philosophy of timeless aesthetic value.',
      premiumIntegrity: 'Premium Quality',
      premiumDesc: 'Using only medical-grade materials to ensure the highest safety for your pets.',
      globalConcierge: 'Global Service',
      globalDesc: 'A seamless delivery experience accompanied by our official product warranty.',
      directory: 'Menu',
      signedOut: 'Signed out successfully',
    }
  }
};
