import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'th' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set) => ({
      language: 'th',
      setLanguage: (lang) => set({ language: lang }),
    }),
    {
      name: 'duit-language-storage',
    }
  )
);

export const translations = {
  th: {
    nav: {
      collections: 'สินค้าทั้งหมด',
      care: 'การดูแลสัตว์เลี้ยง',
      journal: 'บทความ',
      heritage: 'เกี่ยวกับเรา',
      viewStore: 'ดูร้านค้า',
      admin: 'ระบบหลังบ้าน',
    },
    hero: {
      discover: 'เลือกซื้อสินค้า',
      philosophy: 'ความตั้งใจของเรา',
      newCollection: 'คอลเลกชันใหม่ล่าสุด',
      bestSeller: 'สินค้าขายดี',
      livingSeries: 'ซีรีส์เพื่อการอยู่อาศัย',
      slide1Title: 'DESIGNED FOR BETTER LIVING.',
      slide1Sub: 'ยกระดับคุณภาพชีวิตสัตว์เลี้ยงที่คุณรัก ด้วยนวัตกรรมการออกแบบที่เน้นฟังก์ชันและความสวยงามสไตล์เกาหลี',
      slide2Title: 'PRECISION IN EVERY DROP.',
      slide2Sub: 'น้ำพุแมวอัจฉริยะที่ออกแบบมาเพื่อความเงียบสงบและการกรองน้ำที่สะอาดที่สุด',
      slide3Title: 'COZY SPACE FOR EXPLORERS.',
      slide3Sub: 'บ้านพักผ่อนทรงเต็นท์ที่มอบความรู้สึกปลอดภัยและอบอุ่น ออกแบบมาให้เป็นเฟอร์นิเจอร์ชิ้นหรูในบ้านคุณ',
    },
    shop: {
      explore: 'เลือกชมตามหมวดหมู่',
      viewAll: 'ดูทั้งหมด',
      allProducts: 'คอลเลกชันสินค้า',
      eatDrink: 'อาหารและน้ำ',
      furniture: 'เฟอร์นิเจอร์',
      playRest: 'เล่นและพักผ่อน',
      hygiene: 'สุขอนามัย',
      daily: 'ของใช้ทั่วไป',
      aList: 'สินค้าแนะนำ',
      curating: 'กำลังคัดสรรสินค้าชิ้นเอก...',
      freshArrivals: 'สินค้ามาใหม่',
      exploreAll: 'สำรวจทั้งหมด',
      categorySub: 'ค้นหาสิ่งที่ใช่สำหรับเพื่อนตัวน้อยของคุณ',
      selectionSub: 'รวบรวมสินค้าที่ได้รับความนิยมสูงสุด ด้วยดีไซน์ที่โดดเด่นและความงดงามที่ยั่งยืน',
      newArrivalsTitle: 'New In TH.',
      newArrivalsSub: 'สัมผัสวิวัฒนาการล่าสุดของงานดีไซน์จาก Duit รุ่นลิมิเต็ดที่ผลิตขึ้นอย่างประณีต',
      privateCircle: 'ไพรเวท เซอร์เคิล',
      exclusiveClub: 'สิทธิพิเศษสำหรับสมาชิก',
      membershipSub: 'ก้าวเข้าสู่โลกแห่งการดูแลสัตว์เลี้ยงที่ออกแบบมาเพื่อคุณโดยเฉพาะ รับสิทธิประโยชน์และบริการระดับพรีเมียม',
    },
    footer: {
      mission: 'นิยามใหม่ของชีวิตสัตว์เลี้ยงผ่านความแม่นยำทางสถาปัตยกรรมและความสวยงามที่ยั่งยืน ออกแบบในกรุงโซล เพื่อคุณภาพชีวิตที่ดีของสัตว์เลี้ยงทั่วโลก',
      directory: 'สารบัญเว็บไซต์',
      support: 'ความช่วยเหลือ',
      atelier: 'อาเตลิเย่',
      assistance: 'คำถามที่พบบ่อย',
      logistics: 'การจัดส่งสินค้า',
      concierge: 'ติดต่อสอบถาม',
      privacy: 'นโยบายความเป็นส่วนตัว',
      terms: 'ข้อกำหนดและเงื่อนไข',
      representative: 'ตัวแทนจำหน่ายอย่างเป็นทางการ',
    },
    crm: {
      memberCard: 'บัตรสมาชิก Duit Care+',
      tierLevel: 'ระดับสมาชิก',
      points: 'คะแนนสะสม',
      verifiedOwner: 'เจ้าของผลิตภัณฑ์ของแท้',
      welcomeTitle: 'ยินดีต้อนรับสู่',
      welcomeSubtitle: 'เริ่มต้นประสบการณ์สุดพิเศษที่คัดสรรมาเพื่อเพื่อนตัวโปรดของคุณ',
      initDiscovery: 'เริ่มสร้างโปรไฟล์',
      stage01: 'ขั้นตอนที่ 01',
      stage02: 'ขั้นตอนที่ 02',
      definePet: 'สัตว์เลี้ยงของคุณคือ?',
      dog: 'น้องหมา',
      cat: 'น้องแมว',
      detailedPortfolio: 'ข้อมูลประวัติน้อง',
      officialName: 'ชื่อน้อง',
      heritage: 'สายพันธุ์',
      classification: 'ขนาดตัว',
      generate: 'บันทึกและวิเคราะห์ข้อมูล',
      memberPavilion: 'หน้าสมาชิก',
      dashboardSubtitle: 'พื้นที่เฉพาะสำหรับสมาชิก Duit Care+ สัมผัสการดูแลที่คัดสรรมาเพื่อคุณและน้องโดยเฉพาะ',
      tabPersona: 'ข้อมูลน้อง',
      tabCollection: 'สินค้าของฉัน',
      tabPrivileges: 'สิทธิพิเศษ',
      identitySynthesis: 'วิเคราะห์ตัวตนน้อง',
      aiResult: 'ผลวิเคราะห์โดย AI',
      bespokeCuration: 'สินค้าที่แนะนำพิเศษ',
      recommended: 'แนะนำสำหรับน้อง',
      managedCollection: 'รายการสินค้าของคุณ',
      collectionSubtitle: 'จัดการข้อมูลสินค้าและการรับประกันได้ง่ายๆ ในที่เดียว',
      registerNew: 'ลงทะเบียนสินค้าเพิ่ม',
      privilegesPending: 'สิทธิพิเศษใหม่ๆ เร็วๆ นี้',
      invitationPending: 'เรากำลังเตรียมข้อเสนอและรางวัลสุดพิเศษสำหรับคุณ',
      resetProfile: 'สร้างโปรไฟล์ใหม่',
      selectBreed: 'เลือกสายพันธุ์',
      selectSize: 'เลือกขนาด',
    },
    common: {
      search: 'ค้นหา',
      cart: 'ตะกร้าสินค้า',
      petPortfolio: 'ข้อมูลสัตว์เลี้ยง',
      authenticate: 'เข้าสู่ระบบ',
      logout: 'ออกจากระบบ',
      save: 'บันทึกข้อมูล',
      membership: 'สมัครสมาชิก',
      bespokeCare: 'ดูแลอย่างใกล้ชิด',
      earlyAccess: 'สิทธิ์เข้าถึงก่อนใคร',
      heritageDesign: 'ดีไซน์ที่เป็นเอกลักษณ์',
      heritageDesc: 'สร้างสรรค์โดยสถาบันดีไซน์ในเกาหลีใต้ ด้วยปรัชญาความงามที่เหนือกาลเวลา',
      premiumIntegrity: 'คุณภาพระดับพรีเมียม',
      premiumDesc: 'เลือกใช้เฉพาะวัสดุเกรดการแพทย์ที่ดีที่สุด เพื่อความปลอดภัยของสัตว์เลี้ยง',
      globalConcierge: 'บริการดูแลระดับสากล',
      globalDesc: 'ประสบการณ์การจัดส่งที่ไร้รอยต่อ พร้อมการรับประกันสินค้าอย่างเป็นทางการ',
      directory: 'เมนูหลัก',
    }
  },
  en: {
    nav: {
      collections: 'Collections',
      care: 'TH Care',
      journal: 'Journal',
      heritage: 'Heritage',
      viewStore: 'View Store',
      admin: 'Admin Portal',
    },
    hero: {
      discover: 'Discover Collection',
      philosophy: 'Our Philosophy',
      newCollection: 'New Collection 2026',
      bestSeller: 'Best Seller',
      livingSeries: 'Living Series',
      slide1Title: 'DESIGNED FOR BETTER LIVING.',
      slide1Sub: 'Elevate the life of your beloved pets with design innovation focused on function and beauty from South Korea.',
      slide2Title: 'PRECISION IN EVERY DROP.',
      slide2Sub: 'Smart pet fountain designed for silence and the purest water filtration.',
      slide3Title: 'COZY SPACE FOR EXPLORERS.',
      slide3Sub: 'A tent-shaped cozy space providing safety and warmth, designed as luxury home furniture.',
    },
    shop: {
      explore: 'Explore by Category',
      viewAll: 'View All',
      allProducts: 'The Collection',
      eatDrink: 'Eat & Drink',
      furniture: 'Furniture',
      playRest: 'Play & Rest',
      hygiene: 'Hygiene',
      daily: 'Daily Essentials',
      aList: 'The A-List.',
      curating: 'Curating Masterpieces...',
      freshArrivals: 'Fresh Arrivals',
      exploreAll: 'Explore All',
      categorySub: 'Find the perfect piece for your little companion',
      selectionSub: 'A meticulously curated selection of our most coveted pieces, defined by their unparalleled design and enduring appeal.',
      newArrivalsTitle: 'New In TH.',
      newArrivalsSub: 'Experience the latest evolution of the Duit design language. Precision-crafted, limited edition releases.',
      privateCircle: 'Private Circle',
      exclusiveClub: 'Exclusive Club.',
      membershipSub: 'Step into a world of bespoke pet care. Our signature program offers tailormade curation and elite benefits for those who demand the finest for their companions.',
    },
    footer: {
      mission: 'Redefining the boundaries of pet living through architectural precision and enduring aesthetic value. Designed in Seoul, curated for the world.',
      directory: 'Directory',
      support: 'Support',
      atelier: 'Atelier',
      assistance: 'Assistance',
      logistics: 'Logistics',
      concierge: 'Concierge',
      privacy: 'Privacy Charter',
      terms: 'Terms of Service',
      representative: 'Official Representative',
    },
    crm: {
      memberCard: 'Duit Care+ Member',
      tierLevel: 'Membership Tier',
      points: 'Available Points',
      verifiedOwner: 'Verified Duit Atelier Owner',
      welcomeTitle: 'Welcome to',
      welcomeSubtitle: 'Begin a bespoke experience meticulously curated for your beloved companion.',
      initDiscovery: 'Initialize Discovery',
      stage01: 'Stage 01',
      stage02: 'Stage 02',
      definePet: 'Define Your Companion.',
      dog: 'Dog',
      cat: 'Cat',
      detailedPortfolio: 'Detailed Portfolio.',
      officialName: 'Official Name',
      heritage: 'Heritage / Breed',
      classification: 'Size Classification',
      generate: 'Generate & Finalize',
      memberPavilion: 'Member Pavilion',
      dashboardSubtitle: 'Welcome back to your private sanctuary. Experience bespoke care meticulously tailored to your refined lifestyle.',
      tabPersona: 'My Persona',
      tabCollection: 'The Collection',
      tabPrivileges: 'Privileges',
      identitySynthesis: 'Identity Synthesis',
      aiResult: 'AI Profiling Result',
      bespokeCuration: 'Bespoke Curation',
      recommended: 'Recommended',
      managedCollection: 'Your Managed Collection',
      collectionSubtitle: 'Your digital product management and warranty system will be displayed here for continuous high-level care.',
      registerNew: 'Register New Piece',
      privilegesPending: 'Atelier Privileges Pending',
      invitationPending: 'The invitation for your next reward is being crafted.',
      resetProfile: 'Reset Profile',
      selectBreed: 'Select Breed',
      selectSize: 'Select Size',
    },
    common: {
      search: 'Search',
      cart: 'Shopping Bag',
      petPortfolio: 'Pet Portfolio',
      authenticate: 'Authenticate',
      logout: 'Log Out',
      save: 'Save Configuration',
      membership: 'Initialize Membership',
      bespokeCare: 'BESPOKE CARE',
      earlyAccess: 'ATELIER EARLY',
      heritageDesign: 'Heritage Design',
      heritageDesc: 'Crafted by our South Korean design house with a philosophy of enduring aesthetic value.',
      premiumIntegrity: 'Premium Integrity',
      premiumDesc: 'Exclusively using the finest medical-grade materials, engineered for safety and sustainability.',
      globalConcierge: 'Global Concierge',
      globalDesc: 'A seamless delivery experience accompanied by our comprehensive 1-year official guarantee.',
      directory: 'Directory',
    }
  }
};
